api = "0.7"

[extension]
id = "paketo-community/ubi-nodejs-extension"
name = "Ubi Node.js Extension"
version = "0.0.1"
description = "This extension installs the appropriate nodejs runtime via dnf"

[metadata]
  pre-package = "./scripts/build.sh"
  include-files = ["bin/generate", "bin/detect", "bin/run", "extension.toml"]
  [metadata.default-versions]
    node = "18.*.*"

  [[metadata.dependencies]]
    id = "node"
    name = "Ubi Node Extension"
    stacks = ["io.buildpacks.stacks.ubi8"]
    source = "paketocommunity/run-nodejs-18-ubi-base"
    version = "18.1000"

  [[metadata.dependencies]]
    id = "node"
    name = "Ubi Node Extension"
    stacks = ["io.buildpacks.stacks.ubi8"]
    source = "paketocommunity/run-nodejs-16-ubi-base"
    version = "16.1000"
